language: groovy

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
        $HOME/.gradle/caches/*/plugin-resolution/cache.properties
        $HOME/.gradle/caches/*/plugin-resolution/cache.properties.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

env:
  global:
  - secure: N4hWPAcf8mkyHkhxUiHJct8vJ0GXezsLrcykXGGikMwB3chPH4wYJqEeyDx9RtRssl+3/CkmUJwvKShmAJha/0edFJe/kZb5NI+GaAY3g7WUZG7uI5i0XBGDb+B3ijcQWeW2y+YfFs7pzDT/ymBy5m9QjgeIYxbNx9/uddwU/d6xxRAuqzNv5YlEL+yNA7cPhINS8QZlv/BXAaazWEzt1RVXxhviqx4N2dAFlipRnF+5NKovXWwWpmk1xpGun9ULEVNSKnJMz2HN9zxVfTAgfzFRHLH3baY1mLecHvMJSvpRsUXV8Jh7LzxKMTsHC3HvdqfhbMDUv6i4ciygRbw7A2foj0TJ3h8oHEds+Qb3wAIoG3EEvBUDjl/UhOaObJVjmQZjvK1XiGjV5/nRukuRZr8n4+a2JGJiDAQW6rfVJwaHGEwKxZ+nolbhtELAdiKNEdWdBHg/pJjJ/bdWDI8zfGNhkm44f+Bdz9sYy+s6unQluBOZbr2Q8tX/bBYIqGz/AAZFa7oLFH0Deas1oBOhjhFiWUnHjCAMZjhtCAiVA0oUKxpe+4mJBy7WHrfmyxjMR/3mcdCajaY8VwULBfdofc2Ll4WN2l2EVvps3IfKBtS6Q0509jC/jRY9G2mxEBOknZvSdCKfv3aCKLJ39lZoHyIFj/pN1kOjnrIGGlirtAg=
  - secure: ZLh3pIVHpOoSKSLtTNzIdDwxS/SvQe64J4AliVr/XBDTbjazQ+rvbmTdVaa/G3+lZovP2dnycwoTeflaemlRTzngcjVnUtK9hJp8VyV+FFmgLgDJRBVoOJFUGlRKEynpszJ+BTgM1zecNoAmUl9BS4vvx1k6iczgEFAqIbXbAQNvKHrNgmRzlLFv9ImflmfbBQ8E65COQCAfqg8CcWjf/cZH74BYOkXNr9To0rZYaxfLA6TGhxYrxryifPHtdBZ1mijUGj8IunnwZrkXOaW4chOBocXaNfdjfyt9c+pmFOrqFcUDwqEO7KqwG5MnCRilNaMJO+pIkDdA6TFS404BBBDiXNVCIFBCJ5Yb4i/zwTuLhX1/gi/9i6ObBMklcgDVgoBR8VEB6yOSqj+OmKsc1F2zlMK2WaibsKi4vomCAR/2KqwrlbklJvtVuQqSgqwmourtEuuCLdXjFHwp7dtgWwPoJe9eH9xzoZ4CeIbu7f4/+/BHhkAcCpfRPkxdj0wKcBS/lqrIemzQEi9wKm9ktS/je/LSlAtz7+/5UIqWCooB1YrGlrn1YU5mYpp8XOcVUqoYVFmH/2J5E99hTL0My/As9m+FkZr7VzQIiWf8h1J42pS0kGSQoSfwo5KlJjTR3TMoRXSuJkasoM4v9Q0Nt83S1XFybm2bImnLvl2GNHQ=
  - secure: DRVGtaHlV11hRFbfLVueXiQovFUmcBd92sI7Ot9HLVM8yZY1N7GzN4f9cr/OLm4a0ROUOaOa05j/dqL/7zkoG2rSPfOWcBNDvxEiIarVFh393zs3kbn+Qk8OLVF5jg7WHGV5PM/9gjJAdAnr3/IySweXHinhuoRP8/hZhIx56C3v9mq22xHvD8T+Nnm9x13AwNYd48uw1OyDBO1XdGMXEIfPrRFcDyRxokd/FxbryX6kkl5LFjoYY2F12m+LgeZsORVQ5zwHIhqZQ0SFruAy1zsXivEtAc5E8zgIHnI+8HbMq/vUNyvkfciyb4ajg1WW7N4o1A38fHgMLzcDCbcFHDr/sh4uupOraaz7mhsDXIDBj5y24L0nEKmV57trVis8BFIflkA/S7cGO+sYNvRVM/Xzow+xPeKUm9iwke6tzAn71Y0Z2lWaXipvGiYfi3VMTzwTJiR2zTnTlgx1yIydG8+RTd1AOmq4AHpmu2zifY15YGm2VGTO87TMfo1ZWMP9rC5vsmndgnYcdZmFXnmdtmN7k2N1w/XrQ+Ef9fcc7jLorWH4ZcaNtFtlL/GEYj0PMozPceRdT+pi9m9yW+g7Uvrvj2qeKtOtMTK3r7NSAB+dBhaDt9xtyC1qfNUfoxAynF7oO0XkMlouUU4uBQzQ9illKKqsZCk6wmxQi4JDqWk=
  - secure: PZCOTXWpKcTUEFvxWArVBHfJLA3ncArVJVmeWqGEe3f1SH3rDbtnHwAK9MZ+qfQvtmfP5KrsXbechosRGxmY4NzGTuxupzYIeNq3x73RFLYmhDNaf3yIHx5KbLsKm+/y7X11ORKEWTX0Ub68CAc8dyV5iV2CR/1gPpBcL2L7s4xqS9aeeVJj9C2fIOY9uLaCA4g5Vx3opBVLsh7kmBuOgl8ajg24hI4oajQmEatKfxIqZp892cPvOVZgsmR9Y83z6ZL48tmPKsttB5utBe8AQY7TnKwKqo3tFDvTFgO4Vkv+plTJQHU3mULoG7WixL+AvWS6+jhyl2pzhEovDYMHkWi4ozxbO87ZdZp9GIxLihsXmxIunwz7mBolZ1XE6vEwWoVhlWXuZ/fO1udi8UIvcxr01jZwYzVrhvpnpoT/j2goZr+V2kuVXEghm50saRDIP5rAPk4hLj9Q8G3SKObNU0xj8lN/fLM4XIvaZV26kFbDfREBfoV3GL7tHvEdg0gAyjO9d9VIJsomj+/K/e6L1GZCwiN2VgHPJWzgmNMofCFNF7GusA8gju6mO5qWxYZxq0y28p93uE4QJvxZUV9gNZ8fvDrK6xDylB06SDXQqyTxf+GnOv2bRYTTap2PSBgcFScr/Q7jTB65h/e0KlFle8dOEwDMm9E62r4WfS2E6sY=

install:
  # create plugin artifact and deploy it to local maven repository
  - jdk_switcher use oraclejdk7
  - ./gradlew publishToMavenLocal

script:
  # run tests against multiple jdk variants, but use artifact from install step
  - ./gradlew check -i --exclude-task publishToMavenLocal
  - jdk_switcher use oraclejdk8
  - ./gradlew check -i --exclude-task publishToMavenLocal
  - jdk_switcher use openjdk7
  - ./gradlew check -i --exclude-task publishToMavenLocal

before_deploy:
  # back to oraclejdk7; makes sure we publish what we actually tested
  - jdk_switcher use oraclejdk7

deploy:
  - provider: script
    script: ./gradlew publish
  - provider: script
    script: ./gradlew publishPlugins -Dgradle.publish.key=$PLUGIN_PORTAL_KEY -Dgradle.publish.secret=$PLUGIN_PORTAL_SECRET
    on:
      tags: true
